btrfs-progs: fix the filename sanitization of btrfs-image
kdave/btrfs-progs pull request #837
Opened 2024-07-08 05:15 UTC by adam900710

There are several bugs in btrfs-image filename sanitization:

- Ensured kernel path resolution bug
  Since during path resolution btrfs uses hash to find the child inode,
  with garbage filled DIR_ITEMs, it's definitely unable to properly
  resolve the path.

  A warning is added to the man page by the first patch.

- Only the last item got properly sanitized
  All the remaining INODE_REF/DIR_INDEX/DIR_ITEM are not sanitized at
  all.

  This is fixed by the second patch.

- Sanitized filename contains non-ASCII chars
  This is fixed by the third patch.

Finally a new test case is introduced to verify the filename
sanitization behavior of btrfs-image.

2024-07-17 00:24 UTC, kdave requested changes

2024-07-17 01:09 UTC, adam900710 commented on Documentation/btrfs-image.rst
> +	Not recommended as this would introduce new hash mismatch, thus if your
It's name hash, so the "introduce new hash mismatches" is correct.
Although if you want, I can change it to "introduce new filename hash mismatches"

2024-07-17 01:10 UTC, adam900710 commented on tests/misc-tests/065-image-filename/test.sh
> +strings "$tmp" >> "$RESULTS"
Sure, I can go with grep. The "_filename" part is already the marker to ensure an exact match.

2024-07-17 03:10 UTC, adam900710 commented on tests/misc-tests/065-image-filename/test.sh
> +strings "$tmp" >> "$RESULTS"
Anyway, in the newer version I would use a filename list, and grep for each filename.
Furthermore with leading/tailing chars as markers.

2024-07-18 14:30 UTC, kdave approved these changes

2024-07-19 03:29 UTC, merged