Add codespell support (config, workflow to detect/not fix) and make it fix few typos
kdave/btrfs-progs pull request #841
Opened 2024-07-10 21:38 UTC by yarikoptic

I think I have used btrfs-progs directly or not (via btrbk) for years... finally got a motivation/trigger to contribute ;)

More about codespell: https://github.com/codespell-project/codespell .

I personally introduced it to dozens if not hundreds of projects already and so far only positive feedback.

CI workflow has 'permissions' set only to 'read' so also should be safe.

2024-07-10 21:41 UTC, yarikoptic commented
there was also this one which I later ignored since ignored all the tests, but which looks like a legit typo which might be masking desired test error/fail?

```
❯ codespell -C 4 ./tests/fsck-tests/052-init-csum-tree/test.sh
: run_check $SUDO_HELPER fallocate -p -o 4096 -l 4096 "$TEST_MNT/regular_with_holes"
: 
: # And the most complex one, preallocated, written, then hole
: run_check $SUDO_HELPER fallocate  -l 8192 "$TEST_MNT/complex"
> run_check $SUDO_HELPER dd if=/dev/urandom of="$TEST_MNT/compex" \
: 	bs=4k count=1 conv=notrunc status=noxfer > /dev/null 2>&1
: sync
: run_check $SUDO_HELPER fallocate -p -l 4096 "$TEST_MNT/regular_with_holes"
: 
./tests/fsck-tests/052-init-csum-tree/test.sh:46: compex ==> complex
```

see - that there is `compex` not `complex` ... Should I add that fix here too?

2024-07-16 19:27 UTC, kdave commented
Right, `compex` is referring to a file that's used in previous comment so it's a typo and a bug in the test.

2024-07-16 19:39 UTC, kdave commented
Thanks, the spellchecking is definitelly a good thing, the typos sneak in, you could find older commits that fix many of them in documentation, yet you found a lot more.

I've posted review comments, probably more exceptions to be added. The `compex` fix should be a standalone patch as it has functional consequences.

2024-07-16 20:17 UTC, yarikoptic commented
> I've posted review comments, probably more exceptions to be added. 

Sorry, I don't see them -- may be review was not finalized/submitted?

> The `compex` fix should be a standalone patch as it has functional consequences.

- https://github.com/kdave/btrfs-progs/pull/846

2024-07-17 00:23 UTC, kdave commented
Yeah sorry, I'm not yet familiar with the GH reviews, I'll publish them right away.

2024-07-17 00:23 UTC, kdave requested changes

2024-07-17 02:18 UTC, yarikoptic commented on Documentation/Kernel-by-version.rst
> +- delayed input happens at unlink time, not in cleaner thread
Would you prefer to slip iput globally or just eg as "delayed iput" only ?

2024-07-17 03:00 UTC, adam900710 commented on Documentation/Kernel-by-version.rst
> +- delayed input happens at unlink time, not in cleaner thread
Please skip `iput` globally. There are also non-delayed iput, and it's pretty a common term used inside kernel too.

2024-07-17 07:18 UTC, yarikoptic commented
- accounted for above review comments
- rebased
- used newer codespell (found few more typos)
- force-pushed

2024-07-17 07:19 UTC, yarikoptic commented on check/main.c
> +			error("chritical: global root [%llu %llu] not up-to-date, unable to check the file system",
brr... I took it the other way around... fixing now...

2024-07-17 18:18 UTC, yarikoptic commented
CI needs a restart or might be event better

- https://github.com/kdave/btrfs-progs/pull/848

merge/rebase

2024-07-18 14:03 UTC, kdave approved these changes

2024-07-18 14:07 UTC, kdave commented
Merged to devel. I'll update the subject lines or changelogs a bit, we're using the prefixes or want to put some description.

2024-07-18 14:07 UTC, closed without merging

2024-07-18 14:28 UTC, kdave commented
After the apt-cache fix everthing works, now we wait for the typos to come.